---
- name: Reto 2
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Instalar los paquetes de PostgreSQL
      yum:
        name:
          - postgresql
          - postgresql-server
        state: latest
  
  

  
